load_model: null

# training settings
num_epochs: 1000
lr_warmup_steps: 10000
lr: 0.0001
lr_patience: 15
lr_min: 1.e-07
lr_factor: 0.8
weight_decay: 0.0
early_stopping_patience: 150
loss_type: MSE
loss_scale_y: 1.0
loss_scale_dy: 1.0
energy_weight: 1.0
force_weight: 1.0

# dataset specific
dataset: QM9
dataset_arg: energy_U0
dataset_root: /path/to/data
derivative: false
split_mode: null

# dataloader specific
reload: 0
batch_size: 32
inference_batch_size: 128
standardize: false
splits: null
train_size: 110000
val_size: 10000
test_size: null
num_workers: 12

# model architecture specific
model: ViSNetBlock
output_model: Scalar
prior_model: Atomref

# architectural specific
embedding_dimension: 512
num_layers: 9
num_rbf: 64
activation: silu
rbf_type: expnorm
trainable_rbf: false
attn_activation: silu
num_heads: 8
cutoff: 5.0
max_z: 100
max_num_neighbors: 32
reduce_op: add
lmax: 2
vecnorm_type: max_min
trainable_vecnorm: false
vertex_type: None

# other specific
ngpus: 1
num_nodes: 1
precision: 32
log_dir: /path/to/logs
task: train
seed: 1
distributed_backend: ddp
redirect: false
accelerator: gpu
test_interval: 10
save_interval: 1